name: Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
          image: yvens/ec2_artifactid
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
  deploy:
    needs: build
    # https://docs.github.com/fr/actions/hosting-your-own-runners/managing-self-hosted-runners/using-self-hosted-runners-in-a-workflow
    runs-on: [self-hosted]
    steps:
      - name: Pull image from docker hub
      # Install docker on the ec2 virtualle machine:https://docs.docker.com/engine/install/ubuntu/
        run: sudo docker pull yvens/ec2_artifactid:latest
      - name: Delete old container
        run: sudo docker rm -f ec2_artifactid-container
      - name: Run docker container
        run: |
          docker-compose up -e \
          MYSQL_DATABASE= ${{ secrets.MYSQL_DATABASE }} \
          MYSQL_ROOT_PASSWORD= ${{ secrets.MYSQL_ROOT_PASSWORD }} \
          MYSQL_PASSWORD= ${{ secrets.MYSQL_PASSWORD }} \
          MYSQL_USER= ${{ secrets.MYSQL_USER }} \
          MYSQL_HOST= ${{ secrets.MYSQL_HOST }}
