name: Deployment

on:
  push:
    branches: ["with_aws_secret_manager"]
  pull_request:
    branches: ["with_aws_secret_manager"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn clean install -Pprod -DskipTests
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: yvens/ec2_artifactid
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  deploy:
    needs: build
    # https://docs.github.com/fr/actions/hosting-your-own-runners/managing-self-hosted-runners/using-self-hosted-runners-in-a-workflow
    runs-on: [self-hosted]
    # Install docker on the ec2 virtualle machine:https://docs.docker.com/engine/install/ubuntu/
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull yvens/ec2_artifactid:latest
      - name: Delete old container
        run: sudo docker rm -f ec2_artifactid-container
      - name: Run docker container
        run: |
          sudo docker run -d -p 8080:8080 \
            --network=spring-mysql-network \
            --network=front-back-network \
            -e MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} \
            -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
            -e MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
            -e MYSQL_USER=${{ secrets.MYSQL_USER }} \
            -e MYSQL_HOST=${{ secrets.MYSQL_HOST }} \
            --name ec2_artifactid yvens/ec2_artifactid
